name: Build Termux Mod (Star Project)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y wget unzip default-jdk git

      - name: Download Apktool
        run: |
          wget https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar -O apktool.jar
          echo -e '#!/bin/sh\njava -jar $PWD/apktool.jar "$@"' > apktool
          chmod +x apktool
          sudo mv apktool /usr/local/bin/
          sudo mv apktool.jar /usr/local/bin/

      - name: Check decoded_star contents
        run: ls -la decoded_star

      - name: Rebuild APK
        run: |
          apktool b decoded_star -o star.apk || (echo "APKTool Failed!" && exit 1)

      - name: Upload built APK
        uses: actions/upload-artifact@v2
        with:
          name: star-apk
          path: star.apk
